apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: ml-system
spec:
  selector:
    app: inference

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort